artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/0/3228ac529e7044d3ba134be7106b45c9/artifacts
end_time: 1629663595673
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3228ac529e7044d3ba134be7106b45c9
run_uuid: 3228ac529e7044d3ba134be7106b45c9
source_name: ''
source_type: 4
source_version: ''
start_time: 1629663595634
status: 4
tags: []
user_id: dat
