[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]

build-backend = "setuptools.build_meta"

# Pytest
[tool.pytest.ini.options]
testpaths=["tests"]
python_files="test_*.py"
addopts="--strict-markers --disable-pytest-warnings"
markers = [
    "training: test that involve training"
]

# Pytest
[tool.coverage.run]
omit = ["app/main.py"]