artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/0/c6609eb015f54095a2d50fd9fdf6f9a3/artifacts
end_time: 1629664456260
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c6609eb015f54095a2d50fd9fdf6f9a3
run_uuid: c6609eb015f54095a2d50fd9fdf6f9a3
source_name: ''
source_type: 4
source_version: ''
start_time: 1629664456230
status: 4
tags: []
user_id: dat
