artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/0/1fd239287aba40c1acfc663d2d618cf4/artifacts
end_time: 1629663995134
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 1fd239287aba40c1acfc663d2d618cf4
run_uuid: 1fd239287aba40c1acfc663d2d618cf4
source_name: ''
source_type: 4
source_version: ''
start_time: 1629663995101
status: 4
tags: []
user_id: dat
