artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/0/f6b931bd7cb34274948e9e145ed9baf6/artifacts
end_time: 1629671113202
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f6b931bd7cb34274948e9e145ed9baf6
run_uuid: f6b931bd7cb34274948e9e145ed9baf6
source_name: ''
source_type: 4
source_version: ''
start_time: 1629671113135
status: 3
tags: []
user_id: dat
