artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/0/ac4e04e0280c4fbaa7f4e98a8b75ff60/artifacts
end_time: 1629663516722
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ac4e04e0280c4fbaa7f4e98a8b75ff60
run_uuid: ac4e04e0280c4fbaa7f4e98a8b75ff60
source_name: ''
source_type: 4
source_version: ''
start_time: 1629663516696
status: 4
tags: []
user_id: dat
