artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/2/9b59c8bc6821430b8522179c2ab8f1db/artifacts
end_time: 1630614481974
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9b59c8bc6821430b8522179c2ab8f1db
run_uuid: 9b59c8bc6821430b8522179c2ab8f1db
source_name: ''
source_type: 4
source_version: ''
start_time: 1630614481912
status: 3
tags: []
user_id: dat
