artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/2/2592f30725734db99b149e52b15a0c1f/artifacts
end_time: 1630614457436
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 2592f30725734db99b149e52b15a0c1f
run_uuid: 2592f30725734db99b149e52b15a0c1f
source_name: ''
source_type: 4
source_version: ''
start_time: 1630614457377
status: 3
tags: []
user_id: dat
