artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/0/b92d250c75624dcaaf6ed6147c58c013/artifacts
end_time: 1629671061389
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b92d250c75624dcaaf6ed6147c58c013
run_uuid: b92d250c75624dcaaf6ed6147c58c013
source_name: ''
source_type: 4
source_version: ''
start_time: 1629671061335
status: 3
tags: []
user_id: dat
