artifact_uri: file:///users/tp/dat/pytorch_practice/flaskapp/model/0/abe3e9540df845c0a9b534a47f948df8/artifacts
end_time: 1629111232348
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: abe3e9540df845c0a9b534a47f948df8
run_uuid: abe3e9540df845c0a9b534a47f948df8
source_name: ''
source_type: 4
source_version: ''
start_time: 1629111140528
status: 3
tags: []
user_id: dat
