artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/1/151b41dc284d4c3b86944cd3d2dd2796/artifacts
end_time: 1629664342992
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 151b41dc284d4c3b86944cd3d2dd2796
run_uuid: 151b41dc284d4c3b86944cd3d2dd2796
source_name: ''
source_type: 4
source_version: ''
start_time: 1629664342942
status: 3
tags: []
user_id: dat
