artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/0/8addcca81983442a9c42af2623689ebb/artifacts
end_time: 1629663483451
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 8addcca81983442a9c42af2623689ebb
run_uuid: 8addcca81983442a9c42af2623689ebb
source_name: ''
source_type: 4
source_version: ''
start_time: 1629663483422
status: 4
tags: []
user_id: dat
