artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/1/118e3b2fc008427a8771199beb95d48e/artifacts
end_time: 1629664431269
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 118e3b2fc008427a8771199beb95d48e
run_uuid: 118e3b2fc008427a8771199beb95d48e
source_name: ''
source_type: 4
source_version: ''
start_time: 1629664431214
status: 3
tags: []
user_id: dat
