artifact_uri: file:///users/tp/dat/pytorch_practice/flaskapp/model/0/5efc2a08e1fc496bbd2698d8c9a998d7/artifacts
end_time: 1629109488445
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 5efc2a08e1fc496bbd2698d8c9a998d7
run_uuid: 5efc2a08e1fc496bbd2698d8c9a998d7
source_name: ''
source_type: 4
source_version: ''
start_time: 1629109376628
status: 4
tags: []
user_id: dat
