artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/0/24fe7a0a9be541a4a8194024372a80d8/artifacts
end_time: 1629671089253
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 24fe7a0a9be541a4a8194024372a80d8
run_uuid: 24fe7a0a9be541a4a8194024372a80d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1629671089184
status: 3
tags: []
user_id: dat
