artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/1/eb001200c0f845d2bb2df0c63327a815/artifacts
end_time: 1630614505691
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: eb001200c0f845d2bb2df0c63327a815
run_uuid: eb001200c0f845d2bb2df0c63327a815
source_name: ''
source_type: 4
source_version: ''
start_time: 1630614481987
status: 3
tags: []
user_id: dat
