artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/1/8f508f168b3c4ccf833d7c9a584fbf1f/artifacts
end_time: 1629664395467
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 8f508f168b3c4ccf833d7c9a584fbf1f
run_uuid: 8f508f168b3c4ccf833d7c9a584fbf1f
source_name: ''
source_type: 4
source_version: ''
start_time: 1629664395417
status: 3
tags: []
user_id: dat
