artifact_uri: file:///users/tp/dat/pytorch_practice/flaskapp/model/0/187cdf8d1139450c9fd082af4c984182/artifacts
end_time: 1629109317564
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 187cdf8d1139450c9fd082af4c984182
run_uuid: 187cdf8d1139450c9fd082af4c984182
source_name: ''
source_type: 4
source_version: ''
start_time: 1629109230227
status: 4
tags: []
user_id: dat
