artifact_uri: file:///users/tp/dat/Recomendation_systems/stores/model/1/fe33d1a807f04a7f90cb83638d43cb02/artifacts
end_time: 1629671137529
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: fe33d1a807f04a7f90cb83638d43cb02
run_uuid: fe33d1a807f04a7f90cb83638d43cb02
source_name: ''
source_type: 4
source_version: ''
start_time: 1629671113215
status: 3
tags: []
user_id: dat
